version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATA= /data/postgres
    volumes:
      - ./.docker/dbdata:/data/db
    restart: unless-stopped
    networks:
      - postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - 5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    restart: unless-stopped

  api:
    build: .
    container_name: api
    restart: unless-stopped
    networks:
      - postgres
    command: yarn start
    volumes:
      - .:/usr/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgadmin: